name: Deploy Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/backend
            # Forzamos limpieza para evitar bloqueos
            git fetch --all
            git reset --hard origin/main
            npm install
            npm run build
            # Usamos el archivo central de infraestructura para el despliegue
            pm2 startOrReload /var/www/infra/ecosystem.config.js --only miles-back --env production
