name: Deploy Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/backend
            git pull origin main
            npm install
            npm run build
            # Zero Downtime: reload para evitar caídas en la API
            pm2 reload miles-back --update-env || pm2 start dist/main.js --name miles-back
